SendsmsWeb/Models/ContactsViewModel.cs
using SendsmsWeb.Contacts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SendsmsWeb.Models
{
    public class ContactsViewModel
    {
        public List<Contact> Contacts { get; set; }
        public List<string> Tags { get; set; }
    }
}

SendsmsWeb/Models/ErrorViewModel.cs
using System;

namespace SendsmsWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SendsmsWeb/Controllers/ContactManagementController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SendsmsWeb.Controllers
{
    [Route("api/contacts")]
    [ApiController]
    public class ContactManagementController : ControllerBase
    {
        [HttpPost]
        public async Task<IActionResult> DeleteContact()
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        public async Task<IActionResult> CreateContact()
        {
            throw new NotImplementedException();
        }
    }
}

SendsmsWeb/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using SendsmsWeb.Contacts;
using SendsmsWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SendsmsWeb.Controllers
{
    public class ContactsController : Controller
    {
        public async Task<IActionResult> Index() => View(new ContactsViewModel
        {
            Contacts = string.IsNullOrWhiteSpace(Request.Query["tag"]) switch
            {
                true => await ContactsDbInterface.GetAllContacts(),
                false => await ContactsDbInterface.GetContactsFromTags(new List<string> { Request.Query["tag"] }, true)
            },
            Tags = await ContactsDbInterface.GetAllTags()
        });

        public IActionResult BuildContact()
        {
            throw new NotImplementedException();
        }
    }
}

SendsmsWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SendsmsWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SendsmsWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SendsmsWeb/Controllers/SmsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SendsmsWeb.Controllers
{
    public class SmsController : Controller
    {
        public IActionResult BuildMessage() => View();

        [HttpPost]
        public async Task<IActionResult> SubmitMessage()
        {
            // Get params
            string Sender, Recipient, Message;
            try
            {
                Sender = !string.IsNullOrWhiteSpace(Request.Form["sender"]) ? Request.Form["sender"] : throw new Exception("Missing required parameter sender");
                Recipient = !string.IsNullOrWhiteSpace(Request.Form["recipient"]) ? Request.Form["recipient"] : throw new Exception("Missing required parameter recipient");
                Message = !string.IsNullOrWhiteSpace(Request.Form["message"]) ? Request.Form["message"] : throw new Exception("Missing required parameter message");
            }
            catch (Exception e)
            {
                ViewData["Title"] = "Error";
                return View("PlainTextView", e.Message);
            }

            // Send message
            string Result = await Program.TwilioSender.SendSms(Sender, Recipient, Message);

            return View("PlainTextView", $"Status: {Result}");
        }

    }
}

SendsmsWeb/Views/Contacts/Index.cshtml
@model ContactsViewModel
@using SendsmsWeb.Contacts
@{
    ViewData["Title"] = "Contacts";
}

<h1>Contacts</h1>

<!-- Main row -->
<div class="row">
    <!-- Filter col -->
    <div class="col col-md-3">

    </div>
    
    <!-- Contacts col -->
    <div class="col col-md-9">
        <!-- Contacts table -->
        <table class="table table-dark">
            <!-- Table header -->
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Telephone number</th>
                    <th>Company &amp; job title</th>
                    <th>Tags</th>
                </tr>
            </thead>
            <!-- Table body -->
            <tbody>
                @foreach (Contact Contact in Model.Contacts)
                {
                    <tr>
                        <td>@Contact.FullName</td>
                        <td>@Contact.PhoneNumber</td>
                        <td>@Contact.JobTitleAndCompany</td>
                        <td>@Html.Raw(Contact.TagsAsLinks)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

SendsmsWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SendsmsWeb/Views/Shared/PlainTextView.cshtml
@model string

<h1>@ViewData["Title"]</h1>
<p>@Model</p>

SendsmsWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - SendSMS Web</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/site.css">

    <link rel="stylesheet" href="https://use.typekit.net/vzl0eib.css" crossorigin="anonymous">

    <meta charset="UTF-8">

    <meta name="theme-color" content="#007bff">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- FontAwesome -->
    <script src="https://kit.fontawesome.com/227f49c19f.js" crossorigin="anonymous"></script>

</head>
<body>
    <!-- Header -->
    <header class="navbar navbar-expand-lg bg-primary container-fluid p-3 mb-5">
        <!-- Branding -->
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <h2>SendSMS Web</h2>
        </a>
        
        <!-- Toggler -->
        <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Sms" asp-action="BuildMessage"><i class="fas fa-plus"></i> New message</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Contacts" asp-action="Index"><i class="fas fa-user"></i> Contacts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-paper-plane"></i> Senders</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-clock"></i> Schedule</a>
                </li>
            </ul>
        </div>
    </header>

    <!-- Main section -->
    <div class="container card bg-dark mt-5 p-3 rounded" style="min-height: 80vh;">
        @RenderBody()
    </div>

    <!-- Footer -->
    <footer class="container-fluid mt-5 p-3">
        <div class="container text-center">&copy; Simen Eilevstjønn @DateTime.UtcNow.Year, MIT License</div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SendsmsWeb/Views/Sms/BuildMessage.cshtml
@{
    ViewData["Title"] = "New message";
}

<div class="p-3">
    <h2>New message</h2>

    <!-- Message form -->
    <form asp-action="SubmitMessage" asp-controller="Sms" asp-area="">

        <!-- Sender field -->
        <div class="form-group mb-2">
            <label for="sender" id="sender-label">Sender</label>
            <input class="form-control" type="text" placeholder="Sender" id="sender" name="sender" aria-labelledby="sender-label">
            <div class="invalid-feedback">
                Invalid alphanumeric sender or telephone number.
            </div>
        </div>

        <!-- Recipient -->
        <div class="form-group mb-2">
            <label for="recipient" id="recipient-label">Recipient</label>
            <input class="form-control" type="text" placeholder="Recipient" id="recipient" name="recipient" aria-labelledby="recipient-label">
            <div class="invalid-feedback">
                Invalid telephone number.
            </div>
        </div>

        <!-- Text area -->
        <div class="form-group mb-2">
            <label for="message" id="message-label">Message</label>
            <textarea class="form-control" placeholder="Message" id="message" name="message" aria-labelledby="message-label" style="height:10rem"></textarea>
            <div class="invalid-feedback">
                Message is too long. Max 16000 characters.
            </div>
        </div>

        <!-- Submit button-->
        <div class="d-flex flex-row-reverse">
            <input type="submit" id="submit" value="Send" class="btn btn-primary"/>
        </div>
    </form>
</div>